ALTER TABLE ITEM DROP CONSTRAINT FK_ITEM_BUYER_ID
ALTER TABLE ITEM DROP CONSTRAINT FK_ITEM_SELLER_ID
ALTER TABLE BUCHJPA31 DROP CONSTRAINT FK_BUCHJPA31_VERLAG_ID
ALTER TABLE BUCHJPA32 DROP CONSTRAINT FK_BUCHJPA32_VERLAG_ID
ALTER TABLE PERSONJPA7 DROP CONSTRAINT FK_PERSONJPA7_ADDR_ID
ALTER TABLE PERSONJPA21 DROP CONSTRAINT FK_PERSONJPA21_ADRESSE_ID
ALTER TABLE PERSONJPA22 DROP CONSTRAINT FK_PERSONJPA22_ADRESSE_ID
ALTER TABLE PERSONJPA99 DROP CONSTRAINT FK_PERSONJPA99_GESCHLECHT_ID
ALTER TABLE PROJEKTJPA4_MITARBEITERJPA4 DROP CONSTRAINT FK_PROJEKTJPA4_MITARBEITERJPA4_mitarbeiterListe_ID
ALTER TABLE PROJEKTJPA4_MITARBEITERJPA4 DROP CONSTRAINT FK_PROJEKTJPA4_MITARBEITERJPA4_projektListe_ID
DROP TABLE MITARBEITERJPA4 CASCADE
DROP TABLE PERSON1 CASCADE
DROP TABLE ADRESSEJPA22 CASCADE
DROP TABLE ITEM CASCADE
DROP TABLE BUCHJPA31 CASCADE
DROP TABLE ADRESSEJPA21 CASCADE
DROP TABLE ADRESSEJPA7 CASCADE
DROP TABLE BUCHJPA32 CASCADE
DROP TABLE GESCHLECHT CASCADE
DROP TABLE CUSTOMER CASCADE
DROP TABLE PROJEKTJPA4 CASCADE
DROP TABLE KONTOJPA99 CASCADE
DROP TABLE PERSONJPA7 CASCADE
DROP TABLE PERSONJPA1 CASCADE
DROP TABLE PERSONJPA21 CASCADE
DROP TABLE PERSONJPA22 CASCADE
DROP TABLE VERLAGJPA31 CASCADE
DROP TABLE VERLAGJPA32 CASCADE
DROP TABLE PERSONJPA5 CASCADE
DROP TABLE PERSONJPA99 CASCADE
DROP TABLE PERSONJPA6 CASCADE
DROP TABLE PROJEKTJPA4_MITARBEITERJPA4 CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
